### ISSUE TITLE
Stalling asset uploads

### ISSUE THREAD

**Issue by kurkel** [Bynder/bynder-js-sdk#42]
I'm uploading asset files using the SDKs uploadFile -function and some assets seem to be stalling in their upload. In my code I download a file from another provider as a stream using Axios and pass it to the bynder-js-sdk upload function. This way of uploading assets work for 95% of assets but some fail with an exception thrown from [here]( https://github.com/Bynder/bynder-js-sdk/blob/c1c7f61c135dcb1c08c9d9401d8da9d0f2daa68c/src/bynder-js-sdk.js#L835).

Any idea what might be causing this?

**Comment by danielsequeira** [comment]
Hi @kurkel,

It seems you are exceeding the maximum number of polling attempts in some of your uploads and that's why you are getting this error: https://github.com/Bynder/bynder-js-sdk/blob/master/src/bynder-js-sdk.js#L835.

One of the steps of our upload process it to poll the processed state of the asset that is being uploaded. The SDK has the logic to check if the asset is processed until a maximum of 60 attempts, value defined here: https://github.com/Bynder/bynder-js-sdk/blob/master/src/bynder-js-sdk.js#L814. Sometimes if the asset that you are uploading is bigger than usual or if our customers are overloading our systems with a lot of uploads, it might be that these 60 attempts are not enough, because the asset is still processing.

I would advise you to change the default value of the variable `MAX_POLLING_ATTEMPTS` to a higher number and try again.
